### ISSUE TITLE
Render a grid of blank widgets for the future plugins

### ISSUE THREAD

**Issue by maxxxxxdlp** [maxxxxxdlp/calendar-stats#7]

**Comment by Durbatuluk1701** [comment]
Clarifying the goal for this one, is this meant to be on the dashboard page?

**Comment by maxxxxxdlp** [comment]
Correct. I should probably improve the descriptions for some of these.

This issue is just about displaying a grid of siluets (which would be occupied in the future), and making it adaptive for different screen sizes
